version: "3.6"

services:

  web:
    image: andrewcodes/space-miner-web:latest
    depends_on:
      - api
    networks:
      - webnet
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first

  api:
    image: andrewcodes/space-miner-api:latest
    depends_on:
      - db
    networks:
      - webnet
      - backend
    ports:
      - "81:80"
    environment:
      NODE_ENV: production
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_URL: mongo
      DB_PORT: 27017
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first

  db:
    image: mongo
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - data-db:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  webnet:
  backend:

volumes:b
  data-db:
